#!/bin/bash

# drop ot on error
set -e

## Declaring some variables
config="$HOME/.config/openbox"
menuold="$config/menu-static.xml"


## Will backup current static menu.xml to menu-static.xml

cp $HOME/.config/openbox/menu.xml $HOME/.config/openbox/menu-static.xml


## Setup New Menu

if [ -f "$menuold" ]
    then
        obmenu-generator -s -c
        notify-send 'Success!' 'A new menu was generated.'
    else
        notify-send 'Ooops!' 'A backup was never made & is required.. Nothing changed.'
fi
